input:
  accept:
    - src: 22.22.22.22/32
      protocol: tcp
      in_interface: eth0
    - src: 33.33.33.33/32
      protocol: tcp
      dport: 53
  drop:
    - src: 44.44.44.44/32
      protocol: tcp
    - src: 55.55.55.55/32
      protocol: tcp
output:
  accept:
    - src: 66.66.66.66/32
      protocol: tcp
    - src: 77.77.77.77/32
      protocol: tcp
  drop:
    - src: 88.88.88.88/32
      protocol: tcp
    - src: 99.99.99.99/32
      protocol: tcp